name: monophony # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: monophony
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  monophony:
    interface: dbus
    bus: session
    name: io.gitlab.zehkira.Monophony
parts:
  libexpat:
    source: https://github.com/libexpat/libexpat.git
    source-tag: R_2_5_0
# ext:updatesnap
#   version-format:
#     format: "R_%M_%m_%R"
    source-subdir: expat
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --without-docbook
    override-prime: |
      echo "skip"
  zlib:
    source: https://github.com/madler/zlib.git
    source-tag: v1.2.13
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
    override-prime: |
      echo "skip"
  monophony:
    after: [ libexpat, zlib, mpris-server ]
    # See 'snapcraft plugins'
    plugin: make
    source: https://gitlab.com/zehkira/monophony.git
    source-subdir: source
    source-tag: 'v2.1.0'
    source-depth: 1
    build-environment:
      - PATH: ${CRAFT_STAGE}/bin:${PATH}
      - PYTHONPATH: ""
    make-parameters:
      - prefix=${CRAFT_PART_INSTALL}
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/monophony.patch
    override-build: |
      pip install nuitka==1.7.10 ordered-set==4.1.0
      export PATH=$HOME/.local/bin:$PATH
      craftctl default
    override-prime: |
      craftctl default
      mkdir -p meta/gui
      cp -r share/icons meta/gui/
      for i in `find meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    parse-info: [share/metainfo/io.gitlab.zehkira.Monophony.metainfo.xml]
    organize:
      usr: .
  deps:
    plugin: nil
    stage-packages:
      - gir1.2-gstreamer-1.0
      - gir1.2-gst-plugins-base-1.0
    prime:
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstAllocators-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstApp-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstAudio-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstGL-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstGLEGL-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstGLWayland-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstGLX11-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstPbutils-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstRtp-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstRtsp-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstSdp-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstTag-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstVideo-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/Gst-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstBase-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstCheck-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstController-1.0.typelib
      - lib/$CRAFT_ARCH_TRIPLET/girepository-1.0/GstNet-1.0.typelib
    organize:
      usr: .
  mpris-server:
    source: https://github.com/alexdelorenzo/mpris_server.git
    source-tag: 'v0.4.3'
# ext:updatesnap
#   version-format:
#     ignore: true
    plugin: python
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    python-packages:
      - ytmusicapi==1.2.0
      - yt-dlp==2023.7.6
    prime:
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg
      - -lib/python3.10/site-packages/gi
      - -lib/python3.10/site-packages/pygtkcompat
      - -lib/python3.10/site-packages/PyG*
      - -lib/python3.10/site-packages/pycairo*
      - -lib/python3.10/site-packages/cairo*
      - -lib/*/*/setup*
      - -lib/*/*/pkg*
      - -lib/*/*/pip*
      - -lib/*/*/_dist*
      - -share
      - -include
apps:
  monophony:
    command: bin/monophony
    desktop: share/applications/io.gitlab.zehkira.Monophony.desktop
    extensions: [gnome]
    common-id: io.gitlab.zehkira.Monophony
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$PYTHONPATH
      GI_TYPELIB_PATH: $SNAP/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$GI_TYPELIB_PATH
    plugs:
      - home
      - network
      - audio-playback
      - network-bind
      - network-status
    slots:
      - mpris
