name: monophony # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.7.1' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: monophony
icon: icon.svg
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages

package-repositories:
  - type: apt
    components: [main, multiverse, restricted, universe]
    suites: [lunar, lunar-backports, lunar-security, lunar-updates]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://security.ubuntu.com/ubuntu
    
parts:
  monophony:
    # See 'snapcraft plugins'
    plugin: make
    source: https://gitlab.com/zehkira/monophony.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-subdir: source
    source-type: git
    build-packages:
      - libpython3.10-dev
      - libexpat1-dev
      - zlib1g
    #stage-packages:
     # - python3-gst-1.0
    build-environment:
      - PATH: ${CRAFT_STAGE}/bin:${PATH}
    override-pull: |
      craftctl default
      sed -i 's|prefix = /usr|prefix=${CRAFT_PART_INSTALL}/usr|' source/Makefile
      sed -i 's|python3 -m nuitka bin/monophony.py --remove-output --clean-cache=all --follow-import-to=monophony -o monophony.bin|python3 -m nuitka bin/monophony.py --remove-output --clean-cache=all --follow-import-to=monophony -o monophony.bin --static-libpython=no|' source/Makefile
      pip install --target=$CRAFT_PART_INSTALL/usr/lib/python3/dist-packages yt-dlp==2023.3.4
      pip install --target=$CRAFT_PART_INSTALL/usr/lib/python3/dist-packages ytmusicapi==0.25.2
      pip install --target=$CRAFT_PART_INSTALL/usr/lib/python3/dist-packages requests==2.28.2
      pip install setuptools
      pip install --target=$CRAFT_PART_INSTALL/usr/lib/python3/dist-packages mpris_server==0.4.1
    override-build: |
      pip install nuitka
      craftctl default
    parse-info: [usr/share/metainfo/io.gitlab.zehkira.Monophony.metainfo.xml]
  cleanup:
    after: [ monophony ]
    plugin: nil
    override-prime: |
      craftctl default
      cd $CRAFT_PRIME
      rm -rf usr/lib/*/libgir* usr/lib/python* usr/share/doc usr/share/pkgconfig usr/share/man usr/lib/$CRAFT_ARCH_TRIPLET

apps:
  monophony:
    command: usr/bin/monophony
    desktop: usr/share/applications/io.gitlab.zehkira.Monophony.desktop
    extensions: [gnome]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - home
    slots:
      - mpris
