name: monophony # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.7.1' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: monophony
icon: icon.svg
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
    
parts:
  libexpat:
    source: https://github.com/libexpat/libexpat.git
    source-tag: R_2_5_0
    source-subdir: expat
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --without-docbook
    override-prime: |
      echo 'Skip'
  zlib:
    source: https://github.com/madler/zlib.git
    source-tag: v1.2.13
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
    override-prime: |
      echo 'Skip'
  monophony:
    after: [ libexpat, zlib ]
    # See 'snapcraft plugins'
    plugin: make
    source: https://gitlab.com/zehkira/monophony.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-subdir: source
    source-type: git
    stage-packages:
      - libgstreamer1.0-0
    build-environment:
      - PATH: ${CRAFT_STAGE}/bin:${PATH}
      - PYTHONPATH: ${CRAFT_STAGE}/lib/python3.10/site-packages:$PYTHONPATH
    override-pull: |
      craftctl default
      pip install nuitka
      sed -i 's|prefix = /usr|prefix=${CRAFT_PART_INSTALL}/|' source/Makefile
      sed -i 's|python3 -m nuitka bin/monophony.py --remove-output --clean-cache=all --follow-import-to=monophony -o monophony.bin|nuitka bin/monophony.py --remove-output --clean-cache=all --follow-import-to=monophony -o monophony.bin --static-libpython=no|' source/Makefile
    override-build: |
      pip install nuitka ordered-set
      export PATH=$HOME/.local/bin:$PATH
      craftctl default
    parse-info: [usr/share/metainfo/io.gitlab.zehkira.Monophony.metainfo.xml]
  cleanup:
    after: [ monophony ]
    plugin: nil
    override-prime: |
      craftctl default
      cd $CRAFT_PRIME
      rm -rf usr/lib/*/libgir* usr/lib/python* usr/share/doc usr/share/pkgconfig usr/share/man usr/lib/$CRAFT_ARCH_TRIPLET
  mpris_server:
    source: https://github.com/alexdelorenzo/mpris_server.git
    source-tag: 'v0.4.3'
    plugin: python
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""    
    stage:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.cshordered-set
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg
    python-packages:  
      - requests
      - ytmusicapi
      - yt-dlp
      - lxml
      - MarkupSafe
      - appdirs
      - Jinja2

apps:
  monophony:
    command: bin/monophony
    desktop: share/applications/io.gitlab.zehkira.Monophony.desktop
    extensions: [gnome]
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$PYTHONPATH
    plugs:
      - home
    slots:
      - mpris
