name: monophony
base: core22 
adopt-info: monophony
grade: stable 
confinement: strict 
compression: lzo
source-code: https://gitlab.com/zehkira/monophony
website: https://github.com/soumyaDghosh/monophony-snap
issues: https://github.com/soumyaDghosh/monophony-snap/issues

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

plugs:
  ffmpeg-2204:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2204

slots:
  monophony:
    interface: dbus
    bus: session
    name: io.gitlab.zehkira.Monophony
  mpris:
    interface: mpris
    name: Monophony

parts:
  libexpat:
    source: https://github.com/libexpat/libexpat.git
    source-tag: 'R_2_6_0'
# ext:updatesnap
#   version-format:
#     ignore: true
    source-subdir: expat
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --without-docbook
    override-prime: ''

  zlib:
    source: https://github.com/madler/zlib.git
    source-tag: 'v1.3.1'
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
    override-prime: ''

  monophony:
    after: [ libexpat, zlib ]
    # See 'snapcraft plugins'
    plugin: python
    source: https://gitlab.com/zehkira/monophony.git
    source-subdir: source
    source-tag: 'v2.15.0'
    source-depth: 1
    python-packages:
      - yt-dlp==2024.07.02
    override-pull: |
      craftctl default
      sed -i "s|'share/locale'|'usr/share/locale'|" ${CRAFT_PART_SRC_WORK}/bin/monophony.py
      sed -i "/pip install/d" ${CRAFT_PART_SRC_WORK}/Makefile
      sed -i "s|3.11|3.10|" ${CRAFT_PART_SRC_WORK}/pyproject.toml
      sed -i 's|https://gitlab.com/zehkira/monophony/-/issues|https://github.com/soumyaDghosh/monophony-snap/issues|' ${CRAFT_PART_SRC_WORK}/monophony/frontend/windows/main_window.py
    override-build: |
      craftctl default
      cd ${CRAFT_PART_SRC_WORK}
      make prefix=${CRAFT_PART_INSTALL}/usr install
    parse-info: [usr/share/metainfo/io.gitlab.zehkira.Monophony.metainfo.xml]
    organize:
      bin: usr/bin
      lib/python3.10/site-packages: usr/lib/python3/dist-packages
    prime:
      - -share
      - -lib64
      - -include
      - -lib
      - -usr/bin/pip*
      - -usr/bin/Activate*
      - -usr/bin/activate*
      - -usr/bin/python*
      - -pyvenv.cfg

  deps:
    plugin: nil
    stage-packages:
      - gir1.2-gstreamer-1.0
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gst-plugins-bad-1.0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstAllocators-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstApp-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstAudio-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstGL-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstGLEGL-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstGLWayland-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstGLX11-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstPbutils-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstRtp-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstRtsp-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstSdp-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstTag-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstVideo-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/Gst-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstBase-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstCheck-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstController-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstNet-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstBadAudio-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstCodecs-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstInsertBin-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstMpegts-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstPlay-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstPlayer-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstTranscoder-1.0.typelib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0/GstWebRTC-1.0.typelib

apps:
  monophony:
    command: usr/bin/monophony
    desktop: usr/share/applications/io.gitlab.zehkira.Monophony.desktop
    extensions: [gnome]
    common-id: io.gitlab.zehkira.Monophony
    environment:
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
    plugs:
      - network
      - audio-playback
      - network-status
      - screen-inhibit-control
