name: monophony # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: monophony
#icon: icon.svg
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
    
parts:
  libexpat:
    source: https://github.com/libexpat/libexpat.git
    source-tag: R_2_5_0
    source-subdir: expat
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --without-docbook
  zlib:
    source: https://github.com/madler/zlib.git
    source-tag: v1.2.13
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
  monophony:
    after: [ libexpat, zlib, mpris-server ]
    # See 'snapcraft plugins'
    plugin: make
    source: https://gitlab.com/zehkira/monophony.git
    source-subdir: source
    source-type: git
    stage-packages:
      - gir1.2-gstreamer-1.0
    build-environment:
      - PATH: ${CRAFT_STAGE}/bin:${PATH}
      - PYTHONPATH: ${CRAFT_STAGE}/lib/python3.10/site-packages:$PYTHONPATH
    override-pull: |
      craftctl default
      pip install nuitka
      sed -i 's|prefix = /usr|prefix = ${CRAFT_PART_INSTALL}|' source/Makefile
      sed -i 's|python3 -m nuitka bin/monophony.py --remove-output --clean-cache=all --follow-import-to=monophony -o monophony.bin|python3 -m nuitka bin/monophony.py --remove-output --clean-cache=all --follow-import-to=monophony -o monophony.bin --static-libpython=no|' source/Makefile
    override-build: |
      pip install nuitka ordered-set
      export PATH=$HOME/.local/bin:$PATH
      craftctl default
    parse-info: [share/metainfo/io.gitlab.zehkira.Monophony.metainfo.xml]
    organize:
      usr: .
  mpris-server:
    source: https://github.com/alexdelorenzo/mpris_server.git
    source-tag: 'v0.4.3'
    plugin: python
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""    
    python-packages:  
      - requests
      - ytmusicapi
      - yt-dlp
      - lxml
      - MarkupSafe
      - appdirs
      - Jinja2
  cleanup:
    after: [ monophony, mpris-server ]
    plugin: nil
    prime:
      - -lib/x86_64-linux-gnu/glib*
      - -lib/x86_64-linux-gnu/libgio*
      - -lib/x86_64-linux-gnu/libglib*
      - -lib/x86_64-linux-gnu/libgmodule*
      - -lib/x86_64-linux-gnu/libgobject*
      - -lib/x86_64-linux-gnu/libgthread*
      - -share/doc/*
      - -share/glib-2.0
      - -share/lintian
      - -lib/x86_64-linux-gnu/girepository-1.0/GIRepository-2.0.typelib
      - -lib/x86_64-linux-gnu/girepository-1.0/GLib-2.0.typelib
      - -lib/x86_64-linux-gnu/girepository-1.0/GModule-2.0.typelib
      - -lib/x86_64-linux-gnu/girepository-1.0/GObject-2.0.typelib
      - -lib/x86_64-linux-gnu/girepository-1.0/Gio-2.0.typelib
      - -lib/x86_64-linux-gnu/libgirepository*
      - -lib/x86_64-linux-gnu/libdw*
      - -lib/x86_64-linux-gnu/libunwind*    
      - -bin/activate
      - -bin/activate.cshordered-set
      - -bin/activate.fish
      - -bin/activate.csh
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg
      - -lib/python3.10/site-packages/gi
      - -lib/python3.10/site-packages/pygtkcompat
      - -lib/python3.10/site-packages/PyG*
      - -lib/python3.10/site-packages/pycairo*
      - -share
      - -include     
apps:
  monophony:
    command: bin/monophony
    desktop: share/applications/io.gitlab.zehkira.Monophony.desktop
    extensions: [gnome]
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$PYTHONPATH
    plugs:
      - home
    slots:
      - mpris
