name: 🧪 Test snap can be built on x86_64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snapcore/action-build@v1
        id: build
      - uses: actions/upload-artifact@v3
        with:
          name: monophony
          path: ${{ steps.build.outputs.snap }}  
